### ISSUE TITLE
Mock DQ Apps

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/dq-aws-migration#57]
- [x] 1x VPC
- [x] 1x public subnet 
- [x] 1x NAT gateway
- [x] ~~1x s3 gateway~~
- Apps deployed in:
  - [x] #58 Mock dq database
  - [x] #59 Mock tableau internal
  - [x] #60 Mock tableau external
  - [x] #61 mock MDM
  - [x] #62 mock datafeeds 
  - [x] #63 mock ingest
  - [x] #64 mock data pipeline
